// data.js
const DATABASE = {
    "fr": {
        "Combolist 1 (Quotidien)": [
            ["Chien", "Chat"], ["Café", "Thé"], ["Pomme", "Poire"], ["Stylo", "Crayon"], 
            ["Chaise", "Tabouret"], ["Voiture", "Camion"], ["Soleil", "Lune"], ["Pain", "Brioche"], 
            ["Mer", "Océan"], ["Vélo", "Moto"], ["Chemise", "T-shirt"], ["Lunettes", "Lentilles"], 
            ["Montre", "Bracelet"], ["Or", "Argent"], ["Piano", "Guitare"], ["Foot", "Rugby"], 
            ["Tennis", "Ping-pong"], ["Bière", "Cidre"], ["Vin", "Champagne"], ["Beurre", "Margarine"], 
            ["Sel", "Poivre"], ["Sucre", "Édulcorant"], ["Ketchup", "Mayonnaise"], ["Frite", "Chips"], 
            ["Pizza", "Burger"], ["Pâtes", "Riz"], ["Poulet", "Dinde"], ["Saumon", "Thon"], 
            ["Lait", "Yaourt"], ["Fromage", "Crème"], ["Savon", "Gel douche"], ["Brosse à dents", "Dentifrice"], 
            ["Lit", "Canapé"], ["Couette", "Couverture"], ["Oreiller", "Coussin"], ["Fenêtre", "Porte"], 
            ["Sol", "Plafond"], ["Mur", "Clôture"], ["Jardin", "Parc"], ["Forêt", "Jungle"], 
            ["Rivière", "Lac"], ["Pluie", "Neige"], ["Vent", "Tempête"], ["Chaud", "Brûlant"], 
            ["Froid", "Glacé"], ["Manteau", "Veste"], ["Bonnet", "Casquette"], ["Écharpe", "Foulard"], 
            ["Gants", "Moufles"], ["Bottes", "Chaussures"], ["Chaussettes", "Collants"], ["Slip", "Caleçon"], 
            ["Pantalon", "Jean"], ["Jupe", "Robe"], ["Sac à dos", "Valise"], ["Portefeuille", "Porte-monnaie"], 
            ["Clé", "Badge"], ["Carte", "Espèces"], ["Banque", "Coffre-fort"], ["Police", "Gendarmerie"], 
            ["Pompier", "Ambulancier"], ["Médecin", "Infirmier"], ["Professeur", "Élève"], ["École", "Collège"], 
            ["Lycée", "Université"], ["Livre", "Magazine"], ["Journal", "Revue"], ["Lettre", "Carte postale"], 
            ["Email", "SMS"], ["Appel", "Visio"], ["Ordinateur", "Tablette"], ["Clavier", "Souris"], 
            ["Écran", "Télévision"], ["Radio", "Podcast"], ["Film", "Série"], ["Acteur", "Comédien"], 
            ["Chanteur", "Musicien"], ["Danse", "Gymnastique"], ["Course", "Marche"], ["Nager", "Plonger"], 
            ["Voler", "Planer"], ["Sauter", "Bondir"], ["Crier", "Hurler"], ["Rire", "Sourire"], 
            ["Pleurer", "Sangloter"], ["Dormir", "Rêver"], ["Manger", "Déguster"], ["Boire", "Avaler"], 
            ["Aimer", "Adorer"], ["Détester", "Haïr"], ["Vrai", "Faux"], ["Oui", "Non"], 
            ["Noir", "Blanc"], ["Rouge", "Bleu"], ["Vert", "Jaune"], ["Orange", "Violet"]
        ],
        "Combolist 2 (Pop Culture & Marques)": [
            ["Batman", "Superman"], ["Marvel", "DC Comics"], ["Star Wars", "Star Trek"], ["Harry Potter", "Seigneur des Anneaux"], 
            ["Netflix", "Disney+"], ["YouTube", "Twitch"], ["Facebook", "Instagram"], ["Twitter", "LinkedIn"], 
            ["Snapchat", "TikTok"], ["WhatsApp", "Messenger"], ["iPhone", "Samsung"], ["Mac", "PC"], 
            ["Windows", "Linux"], ["Google", "Bing"], ["Chrome", "Firefox"], ["PlayStation", "Xbox"], 
            ["Nintendo", "Sega"], ["Mario", "Luigi"], ["Pikachu", "Dracaufeu"], ["Zelda", "Link"], 
            ["Fortnite", "Minecraft"], ["FIFA", "PES"], ["GTA", "Red Dead Redemption"], ["Call of Duty", "Battlefield"], 
            ["Coca-Cola", "Pepsi"], ["Fanta", "Orangina"], ["Sprite", "7up"], ["Red Bull", "Monster"], 
            ["McDonald's", "Burger King"], ["KFC", "Subway"], ["Dominos", "Pizza Hut"], ["Nutella", "Confiture"], 
            ["Oreo", "Granola"], ["KitKat", "Kinder"], ["M&M's", "Smarties"], ["Haribo", "Lutti"], 
            ["Nike", "Adidas"], ["Puma", "Reebok"], ["Zara", "H&M"], ["Gucci", "Louis Vuitton"], 
            ["Rolex", "Casio"], ["Ferrari", "Lamborghini"], ["Audi", "BMW"], ["Mercedes", "Porsche"], 
            ["Renault", "Peugeot"], ["Uber", "Taxi"], ["Airbnb", "Hôtel"], ["Amazon", "AliExpress"], 
            ["Ikea", "Conforama"], ["Carrefour", "Leclerc"], ["Lidl", "Aldi"], ["Visa", "Mastercard"], 
            ["Bitcoin", "Ethereum"], ["Joker", "Harley Quinn"], ["Spider-Man", "Iron Man"], ["Thor", "Hulk"], 
            ["Vampire", "Loup-garou"], ["Zombie", "Fantôme"], ["Sorcière", "Fée"], ["Dragon", "Dinosaure"], 
            ["Alien", "Robot"], ["Pirate", "Ninja"], ["Cowboy", "Indien"], ["Roi", "Reine"], 
            ["Prince", "Princesse"], ["Château", "Palais"], ["Épée", "Sabre"], ["Pistolet", "Fusil"], 
            ["Bombe", "Grenade"], ["Guerre", "Bataille"], ["Paix", "Trêve"], ["Amour", "Amitié"], 
            ["Mariage", "Pacs"], ["Divorce", "Séparation"], ["Bague", "Collier"], ["Boucles d'oreilles", "Piercing"], 
            ["Tatouage", "Cicatrice"], ["Barbe", "Moustache"], ["Cheveux", "Perruque"], ["Chauve", "Rasé"], 
            ["Blond", "Brun"], ["Roux", "Châtain"], ["Yeux", "Regard"], ["Bouche", "Lèvres"], 
            ["Nez", "Narines"], ["Oreille", "Ouïe"], ["Main", "Doigt"], ["Pied", "Orteil"], 
            ["Cœur", "Poumon"], ["Sang", "Veine"], ["Os", "Squelette"], ["Muscle", "Force"]
        ],
        "Combolist 3 (Concepts & Nature)": [
            ["France", "Belgique"], ["Paris", "Marseille"], ["Londres", "New York"], ["Espagne", "Italie"], 
            ["Allemagne", "Angleterre"], ["Chine", "Japon"], ["Canada", "États-Unis"], ["Russie", "Ukraine"], 
            ["Afrique", "Asie"], ["Europe", "Amérique"], ["Nord", "Sud"], ["Est", "Ouest"], 
            ["Gauche", "Droite"], ["Haut", "Bas"], ["Devant", "Derrière"], ["Dedans", "Dehors"], 
            ["Ici", "Là-bas"], ["Maintenant", "Demain"], ["Hier", "Avant-hier"], ["Jour", "Nuit"], 
            ["Matin", "Soir"], ["Midi", "Minuit"], ["Heure", "Minute"], ["Seconde", "Instant"], 
            ["Année", "Siècle"], ["Printemps", "Été"], ["Automne", "Hiver"], ["Lundi", "Mardi"], 
            ["Janvier", "Février"], ["Noël", "Pâques"], ["Anniversaire", "Fête"], ["Cadeau", "Surprise"], 
            ["Gateau", "Tarte"], ["Bougie", "Lampe"], ["Feu", "Flamme"], ["Eau", "Glace"], 
            ["Terre", "Sable"], ["Pierre", "Caillou"], ["Montagne", "Colline"], ["Volcan", "Cratère"], 
            ["Île", "Presqu'île"], ["Désert", "Savane"], ["Lion", "Tigre"], ["Éléphant", "Girafe"], 
            ["Singe", "Gorille"], ["Ours", "Panda"], ["Loup", "Renard"], ["Aigle", "Faucon"], 
            ["Pigeon", "Mouette"], ["Perroquet", "Canari"], ["Serpent", "Lézard"], ["Tortue", "Escargot"], 
            ["Grenouille", "Crapaud"], ["Requin", "Dauphin"], ["Baleine", "Orque"], ["Poisson", "Crustacé"], 
            ["Mouche", "Moustique"], ["Abeille", "Guêpe"], ["Fourmi", "Termite"], ["Araignée", "Scorpion"], 
            ["Rose", "Tulipe"], ["Arbre", "Buisson"], ["Feuille", "Branche"], ["Racine", "Tronc"], 
            ["Pomme", "Orange"], ["Banane", "Kiwi"], ["Fraise", "Framboise"], ["Cerise", "Griotte"], 
            ["Citron", "Pamplemousse"], ["Tomate", "Concombre"], ["Carotte", "Patate"], ["Oignon", "Ail"], 
            ["Poireau", "Céleri"], ["Chou", "Salade"], ["Épinard", "Brocoli"], ["Haricot", "Pois"], 
            ["Champignon", "Truffe"], ["Viande", "Poisson"], ["Oeuf", "Omelette"], ["Pain", "Toast"], 
            ["Miel", "Confiture"], ["Chocolat", "Vanille"], ["Fraise", "Chocolat"], ["Café", "Chocolat chaud"], 
            ["Eau plate", "Eau gazeuse"], ["Jus d'orange", "Jus de pomme"], ["Sirop", "Diabolo"], 
            ["Cocktail", "Mocktail"], ["Whisky", "Rhum"], ["Vodka", "Gin"], ["Pastis", "Ricard"]
        ]
    },
    "en": {
        "Combolist 1 (Daily Life)": [
            ["Dog", "Cat"], ["Coffee", "Tea"], ["Apple", "Pear"], ["Pen", "Pencil"], 
            ["Chair", "Stool"], ["Car", "Truck"], ["Sun", "Moon"], ["Bread", "Bun"], 
            ["Sea", "Ocean"], ["Bike", "Motorbike"], ["Shirt", "T-shirt"], ["Glasses", "Contacts"], 
            ["Watch", "Bracelet"], ["Gold", "Silver"], ["Piano", "Guitar"], ["Soccer", "Rugby"], 
            ["Tennis", "Ping-pong"], ["Beer", "Cider"], ["Wine", "Champagne"], ["Butter", "Margarine"], 
            ["Salt", "Pepper"], ["Sugar", "Sweetener"], ["Ketchup", "Mayo"], ["Fries", "Chips"], 
            ["Pizza", "Burger"], ["Pasta", "Rice"], ["Chicken", "Turkey"], ["Salmon", "Tuna"], 
            ["Milk", "Yogurt"], ["Cheese", "Cream"], ["Soap", "Shower Gel"], ["Toothbrush", "Toothpaste"], 
            ["Bed", "Sofa"], ["Duvet", "Blanket"], ["Pillow", "Cushion"], ["Window", "Door"], 
            ["Floor", "Ceiling"], ["Wall", "Fence"], ["Garden", "Park"], ["Forest", "Jungle"], 
            ["River", "Lake"], ["Rain", "Snow"], ["Wind", "Storm"], ["Hot", "Burning"], 
            ["Cold", "Freezing"], ["Coat", "Jacket"], ["Beanie", "Cap"], ["Scarf", "Shawl"], 
            ["Gloves", "Mittens"], ["Boots", "Shoes"], ["Socks", "Tights"], ["Briefs", "Boxers"], 
            ["Pants", "Jeans"], ["Skirt", "Dress"], ["Backpack", "Suitcase"], ["Wallet", "Purse"], 
            ["Key", "Badge"], ["Card", "Cash"], ["Bank", "Safe"], ["Police", "Sheriff"], 
            ["Firefighter", "Paramedic"], ["Doctor", "Nurse"], ["Teacher", "Student"], ["School", "College"], 
            ["High School", "University"], ["Book", "Magazine"], ["Newspaper", "Review"], ["Letter", "Postcard"], 
            ["Email", "SMS"], ["Call", "Video Call"], ["Computer", "Tablet"], ["Keyboard", "Mouse"], 
            ["Screen", "TV"], ["Radio", "Podcast"], ["Movie", "Series"], ["Actor", "Comedian"], 
            ["Singer", "Musician"], ["Dance", "Gymnastics"], ["Run", "Walk"], ["Swim", "Dive"], 
            ["Fly", "Glide"], ["Jump", "Leap"], ["Scream", "Shout"], ["Laugh", "Smile"], 
            ["Cry", "Sob"], ["Sleep", "Dream"], ["Eat", "Taste"], ["Drink", "Swallow"], 
            ["Love", "Adore"], ["Hate", "Loathe"], ["True", "False"], ["Yes", "No"], 
            ["Black", "White"], ["Red", "Blue"], ["Green", "Yellow"], ["Orange", "Purple"]
        ],
        "Combolist 2 (Pop Culture & Brands)": [
            ["Batman", "Superman"], ["Marvel", "DC Comics"], ["Star Wars", "Star Trek"], ["Harry Potter", "LOTR"], 
            ["Netflix", "Disney+"], ["YouTube", "Twitch"], ["Facebook", "Instagram"], ["Twitter", "LinkedIn"], 
            ["Snapchat", "TikTok"], ["WhatsApp", "Messenger"], ["iPhone", "Samsung"], ["Mac", "PC"], 
            ["Windows", "Linux"], ["Google", "Bing"], ["Chrome", "Firefox"], ["PlayStation", "Xbox"], 
            ["Nintendo", "Sega"], ["Mario", "Luigi"], ["Pikachu", "Charizard"], ["Zelda", "Link"], 
            ["Fortnite", "Minecraft"], ["FIFA", "PES"], ["GTA", "Red Dead"], ["Call of Duty", "Battlefield"], 
            ["Coke", "Pepsi"], ["Fanta", "Sprite"], ["Dr Pepper", "Mountain Dew"], ["Red Bull", "Monster"], 
            ["McDonald's", "Burger King"], ["KFC", "Subway"], ["Dominos", "Pizza Hut"], ["Nutella", "Jam"], 
            ["Oreo", "Cookie"], ["KitKat", "Snickers"], ["M&M's", "Skittles"], ["Gummy Bear", "Jelly Bean"], 
            ["Nike", "Adidas"], ["Puma", "Reebok"], ["Zara", "H&M"], ["Gucci", "Prada"], 
            ["Rolex", "Casio"], ["Ferrari", "Lamborghini"], ["Audi", "BMW"], ["Mercedes", "Porsche"], 
            ["Ford", "Chevrolet"], ["Uber", "Taxi"], ["Airbnb", "Hotel"], ["Amazon", "eBay"], 
            ["Ikea", "Walmart"], ["Target", "Costco"], ["Tesco", "Aldi"], ["Visa", "Mastercard"], 
            ["Bitcoin", "Ethereum"], ["Joker", "Harley Quinn"], ["Spider-Man", "Iron Man"], ["Thor", "Hulk"], 
            ["Vampire", "Werewolf"], ["Zombie", "Ghost"], ["Witch", "Fairy"], ["Dragon", "Dinosaur"], 
            ["Alien", "Robot"], ["Pirate", "Ninja"], ["Cowboy", "Indian"], ["King", "Queen"], 
            ["Prince", "Princess"], ["Castle", "Palace"], ["Sword", "Saber"], ["Gun", "Rifle"], 
            ["Bomb", "Grenade"], ["War", "Battle"], ["Peace", "Truce"], ["Love", "Friendship"], 
            ["Marriage", "Union"], ["Divorce", "Breakup"], ["Ring", "Necklace"], ["Earrings", "Piercing"], 
            ["Tattoo", "Scar"], ["Beard", "Mustache"], ["Hair", "Wig"], ["Bald", "Shaved"], 
            ["Blonde", "Brunette"], ["Redhead", "Brown"], ["Eyes", "Gaze"], ["Mouth", "Lips"], 
            ["Nose", "Nostrils"], ["Ear", "Hearing"], ["Hand", "Finger"], ["Foot", "Toe"], 
            ["Heart", "Lung"], ["Blood", "Vein"], ["Bone", "Skeleton"], ["Muscle", "Strength"]
        ],
        "Combolist 3 (Concepts & Nature)": [
            ["France", "Belgium"], ["Paris", "London"], ["London", "New York"], ["Spain", "Italy"], 
            ["Germany", "England"], ["China", "Japan"], ["Canada", "USA"], ["Russia", "Ukraine"], 
            ["Africa", "Asia"], ["Europe", "America"], ["North", "South"], ["East", "West"], 
            ["Left", "Right"], ["Up", "Down"], ["Front", "Back"], ["Inside", "Outside"], 
            ["Here", "There"], ["Now", "Tomorrow"], ["Yesterday", "Before"], ["Day", "Night"], 
            ["Morning", "Evening"], ["Noon", "Midnight"], ["Hour", "Minute"], ["Second", "Moment"], 
            ["Year", "Century"], ["Spring", "Summer"], ["Autumn", "Winter"], ["Monday", "Tuesday"], 
            ["January", "February"], ["Christmas", "Easter"], ["Birthday", "Party"], ["Gift", "Surprise"], 
            ["Cake", "Pie"], ["Candle", "Lamp"], ["Fire", "Flame"], ["Water", "Ice"], 
            ["Earth", "Sand"], ["Stone", "Pebble"], ["Mountain", "Hill"], ["Volcano", "Crater"], 
            ["Island", "Peninsula"], ["Desert", "Savanna"], ["Lion", "Tiger"], ["Elephant", "Giraffe"], 
            ["Monkey", "Gorilla"], ["Bear", "Panda"], ["Wolf", "Fox"], ["Eagle", "Falcon"], 
            ["Pigeon", "Seagull"], ["Parrot", "Canary"], ["Snake", "Lizard"], ["Turtle", "Snail"], 
            ["Frog", "Toad"], ["Shark", "Dolphin"], ["Whale", "Orca"], ["Fish", "Crab"], 
            ["Fly", "Mosquito"], ["Bee", "Wasp"], ["Ant", "Termite"], ["Spider", "Scorpion"], 
            ["Rose", "Tulip"], ["Tree", "Bush"], ["Leaf", "Branch"], ["Root", "Trunk"], 
            ["Apple", "Orange"], ["Banana", "Kiwi"], ["Strawberry", "Raspberry"], ["Cherry", "Berry"], 
            ["Lemon", "Grapefruit"], ["Tomato", "Cucumber"], ["Carrot", "Potato"], ["Onion", "Garlic"], 
            ["Leek", "Celery"], ["Cabbage", "Lettuce"], ["Spinach", "Broccoli"], ["Bean", "Pea"], 
            ["Mushroom", "Truffle"], ["Meat", "Fish"], ["Egg", "Omelet"], ["Bread", "Toast"], 
            ["Honey", "Jam"], ["Chocolate", "Vanilla"], ["Strawberry", "Chocolate"], ["Coffee", "Hot Cocoa"], 
            ["Still Water", "Sparkling Water"], ["Orange Juice", "Apple Juice"], ["Syrup", "Soda"], 
            ["Cocktail", "Mocktail"], ["Whisky", "Rum"], ["Vodka", "Gin"], ["Beer", "Wine"]
        ]
    }
};